<a href="https://colab.research.google.com/github/EstebanGomez1/CursoPyTorch/blob/main/cuaderno1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


Tensors


In [11]:
#scalar
scalar = torch.tensor(7)
scalar
#dim
print(scalar.ndim)
#get tensor back as python int
print(scalar.item())
#vector
vector = torch.tensor([7,7])
vector
vector.shape
#matrix
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

0
7


tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
#tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)

# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


(tensor([[0.8847, 0.8419, 0.9976, 0.7762],
         [0.2780, 0.0481, 0.4612, 0.7523],
         [0.8006, 0.6960, 0.7498, 0.6049]]),
 torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)